### ISSUE TITLE
can`t use docker command in container.

### ISSUE THREAD

**Issue by vzerzhang** [pschiffe/pcs#2]
use command: `docker run -dt --privileged --net=host -v /sys/fs/cgroup:/sys/fs/cgroup -v /etc/localtime:/etc/localtime:ro -v /run/docker.sock:/run/docker.sock:ro -v /usr/bin/docker:/usr/bin/docker:ro --name pcs pschiffe/pcs`. 
start pcs container, then into container, can not use docker command, error is 
```
docker exec -it pcs bash
[root@install-105 /]# docker  ps
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[root@install-105 /]# ll /var/run/docker.sock
ls: cannot access '/var/run/docker.sock': No such file or directory
[root@install-105 /]#
```
i guess the container entrypoint `CMD [ "/usr/lib/systemd/systemd", "--system" ]`, when systemd service start ,will remount /run folder??

**Comment by pschiffe** [comment]
I've updated the container, can you try now with parameter `-v /run/docker.sock:/var/docker.sock:ro`?
